# Sample .travis.yml for R projects

language: r
r: 
    - devel
cache: packages

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_github("Bioconductor/BiocGenerics", ref = "master")'
  - R -e 'install.packages("reshape2")'
  - R -e 'install.packages("covr")'
  - R -e 'devtools::install_github("RGLab/flowClust", ref = "bioc")'
  - R -e 'devtools::install_github("RGLab/flowWorkspace", ref = "cytoverse")'
  - R -e 'devtools::install_github("RGLab/ggcyto", ref = "cytoverse")'
  - R -e 'devtools::install_github("RGLab/openCyto", ref = "cytoverse")'
  - tlmgr install index

install:
  - R -e 'devtools::install_deps(dep = T, upgrade = "always")'

group: stable
warnings_are_errors: false 
sudo: required 

bioc_required: true

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - r-lib/covr

after_success: 
  - Rscript -e 'library(covr); codecov()'
